---
- name: EDA | Insights | Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002

  rules:
    - name: EDA | Insights | Remediate Malware with Ansible
      condition: event.payload is defined and event.payload.event_type == 'detected-malware'
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights Malware playbook"
            organization: "{{ organization | default('Default') }}"
            job_args:
              extra_vars:
                insights_mal_data: "{{ event.payload.events }}"
                insights_event_host_data: "{{ event.payload.context }}"
                insights_event_target_host: "{{ event.payload.context.inventory_id }}"

    - name: EDA | Insights | New system registered
      condition: event.payload is defined and event.payload.event_type == 'new-system-registered'
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights New system playbook"
            organization: "{{ organization | default('Default') }}"
            job_args:
              extra_vars:
                insights_event_type: "{{ event.payload.event_type }}"
                insights_event_data: "{{ event.payload.events }}"
                insights_event_host_data: "{{ event.payload.context }}"
                insights_event_target_host: "{{ event.payload.context.inventory_id }}"
                
    - name: EDA | Insights | Remediate Red Hat Insights Advisory with Ansible
      condition: event.payload is defined and event.payload.event_type == 'new-advisory'
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights Advisory playbook"
            organization: "{{ organization | default('Default') }}"
            job_args:
              extra_vars:
                insights_adv_type: "{{ event.payload.event_type }}"
                insights_adv_data: "{{ event.payload.events }}"
                insights_adv_host_data: "{{ event.payload.context }}"
                insights_adv_target_host: "{{ event.payload.context.inventory_id }}"
