---
- name: EDA | Insights | New System Registered
  hosts: localhost
  gather_facts: no
  vars:
    insights_api_url: "https://console.redhat.com/api"
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password }}"

  tasks:
    - name: Wait for security advisorties to be available for new registered system
      pause:
        seconds: 30

    - name: Fetch security advisories for target host
      uri:
        url: "{{ insights_api_url }}/patch/v3/export/systems/{{ insights_event_target_host }}/advisories?filter[advisory_type_name]=security"
        method: GET
        return_content: yes
        headers:
          Accept: "application/json"
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: yes
        validate_certs: yes
        status_code: 200,404
      register: host_advisories
      retries: 10
      delay: 30
      until: host_advisories.status == 200

    - name: Print the no of security advisories
      debug:
        msg: "Found {{ host_advisories.content | from_json | length }} security advisories for {{ insights_event_target_host }}"

    - name: Print the security advisories
      debug:
        var: host_advisories.content

    - name: Generate remediation for target host
      uri:
          url: "{{ insights_api_url }}/remediations/v1/remediations"
          method: POST
          return_content: yes 
          user: "{{ insights_auth_user }}"
          password: "{{ insights_auth_password }}"
          force_basic_auth: yes
          validate_certs: yes
          status_code: 201
          headers:
            Content-Type: "application/json"
            accept: "text/vnd.yaml"
            Connection: "keep-alive"
          body_format: json
          body:
            name: "RHSA - {{ insights_event_target_host }} - {{ now() | string }}"
            auto_reboot: true
            add: "{{ lookup('template','templates/remediation_host_body.j2') }}"
      register: host_remediation
      vars:
        host_advisory_ids: "{{ host_advisories.content | from_json | map(attribute='id') | list }}"
        host_uuid: "{{ insights_event_target_host }}"
      when: host_advisories.content is defined and host_advisories.content | from_json | length > 0