---
- name: EDA | Insights | New Advisory
  hosts: localhost
  gather_facts: no
  vars:
    insights_api_url: "https://console.redhat.com/api"
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password }}"

  tasks:        
    - name: Get list of affected hosts
      uri:
        url: "{{ insights_api_url }}/patch/v3/export/advisories/{{ advisory_id }}/systems"
        method: GET
        return_content: yes
        headers:
          Accept: "application/json"
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: yes
        validate_certs: yes
        status_code: 200
      register: affected_hosts

#    - name: Print the no of affected hosts
#      debug:
#        msg: "Found {{ affected_hosts.content | from_json | length }} affected hosts for advisory {{ advisory_id }}"

#    - name: Print the affected hosts
#      debug:
#        msg: "{{ affected_hosts.content }}"

    - name: Generate remediation for affected hosts
      uri:
          url: "{{ insights_api_url }}/remediations/v1/remediations"
          method: POST
          return_content: yes 
          user: "{{ insights_auth_user }}"
          password: "{{ insights_auth_password }}"
          force_basic_auth: yes
          validate_certs: yes
          status_code: 201
          headers:
            Content-Type: "application/json"
            accept: "text/vnd.yaml"
            Connection: "keep-alive"
          body_format: json
          body:
            name: "RHSA - {{ advisory_id }} - {{ now() | string }}"
            auto_reboot: true
            add: "{{ lookup('template','templates/remediation_advisory_body.j2') }}"
      register: advisory_remediation
      vars:
        advisory_id: "{{ advisory_id }}"
        host_uuids: "{{ affected_hosts.content | from_json | map(attribute='id') | list }}"